### ISSUE TITLE
Each release of the Raiden Wizard needs to download an specific version of the Raiden Client

### ISSUE THREAD

**Issue by lullis** [raiden-network/raiden-installer#73]
Currently, the releases from Raiden Wizard try to download/install the most recent version of the raiden client that it can find on its release pages. This has led to issues for users that were just wanted to keep testing an old version of the client.

To avoid that, we will establish that each release of the Wizard will correspond to one single release of the raiden client.

**Comment by Dominik1999** [comment]
It is a good idea that the Wizard does not download the latest develop anymore. 

Can you help me to understand, what your next steps here are now? 

This issue is related to https://github.com/raiden-network/raiden/issues/5187 right?
Isn't that related to https://github.com/raiden-network/raiden/issues/5187

**Comment by lullis** [comment]
This was implemented today with commit 51f4dbee94710a46a0595826aa60f4bbbf7f67d6.

Basically, each release of the raiden wizard will download one specific version of the raiden client. The client is determined by changing the contents of a configuration file that is included on the distributed wizard.
